version: "3"

services:
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=todos
      - MYSQL_USER=todoapp
      - MYSQL_PASSWORD=plumbus
      - MYSQL_ROOT_PASSWORD=plumbus
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql

  todo-webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mariadb+pymysql://todoapp:plumbus@db/todos?charset=utf8mb4
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
