version: "3"

services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql

  todo-webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mariadb+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}?charset=utf8mb4
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
