# generated by fastapi-codegen:
#   filename:  todo_webapp_api.json
#   timestamp: 2026-10-03T19:07:25+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI, Path
from fastapi.staticfiles import StaticFiles
from pydantic import conint

from models import Error, Todo
from repository import repository

app = FastAPI(
    version="1.0.0",
    title="Swagger Todo App",
    license={"name": "MIT"},
    servers=[{"url": "http://127.0.0.1:8000"}],
)
# This line sets up the serving of the frontend
app.mount("/todoapp", StaticFiles(directory="frontend", html=True), name="static")

repo = repository()


@app.get(
    "/todos",
    response_model=List[Todo],
    responses={"default": {"model": Error}},
    tags=["todo"],
)
def list_todo(limit: Optional[conint(le=100)] = None) -> Union[List[Todo], Error]:
    """
    List all todos
    """
    return repo.fetchAllTodos()


@app.post(
    "/todos",
    response_model=None,
    status_code=201,
    responses={"default": {"model": Error}},
    tags=["todo"],
)
def create_todo(body: Todo) -> Optional[Error]:
    """
    Create a todo
    """
    print(body.name)
    repo.createTodo(body)
    pass


@app.put(
    "/todos",
    response_model=None,
    responses={"default": {"model": Error}},
    tags=["todo"],
)
def update_todo(body: Todo) -> Optional[Error]:
    """
    Update a todo
    """
    repo.updateTodo(body)


@app.get(
    "/todos/{todoId}",
    response_model=Todo,
    responses={"default": {"model": Error}},
    tags=["todos"],
)
def show_todo_by_id(todo_id: str = Path(..., alias="todoId")) -> Union[Todo, Error]:
    """
    Info for a specific todoId
    """
    pass


@app.delete(
    "/todos/{todoId}",
    response_model=None,
    status_code=204,
    responses={"default": {"model": Error}},
    tags=["todo"],
)
def delete_todo(todo_id: str = Path(..., alias="todoId")) -> Optional[Error]:
    """
    Delete a todo
    """
    repo.deleteTodo(todo_id)
    pass
