# generated by fastapi-codegen:
#   filename:  todo_webapp_api.json
#   timestamp: 2026-10-03T19:58:47+00:00

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel


class Todo(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None
    reminder: Optional[date] = None


class Error(BaseModel):
    code: int
    message: str
