# generated by fastapi-codegen:
#   filename:  todo_webapp_api.json
#   timestamp: 2026-10-01T18:36:59+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Todo(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None


class Error(BaseModel):
    code: int
    message: str
