# generated by fastapi-codegen:
#   filename:  todo_webapp_api.json
#   timestamp: 2026-10-03T19:07:25+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, NaiveDatetime


class Todo(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None
    reminder: Optional[NaiveDatetime] = None


class Error(BaseModel):
    code: int
    message: str
